google.sheets.spreadsheet-id=11T9gl1TBBLsUqBW4V9bkDqsJQKgQou1YE_eyNqEeV0c
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=anandkishorereddy111@gmail.com
spring.mail.password=kwzofechgkcxcgew
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

brevo.api.key=${BREVO_API_KEY}
mail.from=${MAIL_FROM}

razorpay.key.id=rzp_test_T8v40JUj6nLL94
razorpay.key.secret=1NwYwhOqXhCp3YRogrr7souM